---

- hosts: all
  become: true
  vars:

  - name: Get the OS platform
    command: cat /etc/redhat-release
    register: redhatRelease

  - name: Print the redhat-release
    debug: msg={{ redhatRelease.stdout }}

  - name: Update packages
    yum: name=* state=latest   

  