---

- hosts: all
  become: true
  tasks:
  
  - name: install python3
    yum:
       name: python3
       state: latest

  - name: install postgresql13 package
    yum:
       name: postgresql13
       state: latest

  - name: install pg_activity
    yum:
       name: pg_activity
       state: latest

