---

- hosts: all
  become: true
  tasks:
  
  - name: install python3
    yum:
       name: python3
       state: absent
 
  - name: install postgresql13 package
    yum:
       name: postgresql
       state: absent
   
  - name: install pg_activity
    yum:
       name: pg_activity
       state: absent
 
